"""Read-only projection of PeerSlate project truth for the owner Control Room.

The Control Room is an owner-only, read-only *projection* of authoritative
project sources. This module derives everything it shows from version-controlled
repository files (governance records, initiative packages, the decision log) plus
optional local Git metadata. It:

* performs no writes and calls no mutation of any kind;
* uses no runtime AI generation (deterministic, source-backed rendering only);
* reads only from fixed, code-owned repository roots — no request input is ever
  turned into a filesystem path, so directory traversal is structurally
  impossible;
* never touches secrets, tokens, connection strings, or the database;
* returns, for every fact, a source path, a best-known timestamp, and a status
  so the UI can distinguish ``ok`` / ``unknown`` / ``unavailable`` / ``partial``.

If a source is missing or malformed, the relevant provider degrades to a truthful
``unavailable`` / ``unknown`` state rather than raising or manufacturing a
favourable status.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.join(ROOT, "docs")
GOV = os.path.join(DOCS, "governance")
INITIATIVES_DIR = os.path.join(DOCS, "initiatives")

# Build-time snapshot (Tier 0): generated by
# scripts/generate_control_room_snapshot.py in the Azure pipeline, before the
# CopyFiles step packages the deployment artifact (which excludes .git). Not
# tracked in git (see .gitignore) — absent in a fresh checkout, present in a
# deployed production artifact and safe to regenerate locally for testing.
SNAPSHOT_PATH = os.path.join(ROOT, "control_room_snapshot.json")
SNAPSHOT_SCHEMA_VERSION = 1

# Status vocabulary shared with the template so colour is never the only signal.
OK = "ok"
UNKNOWN = "unknown"
UNAVAILABLE = "unavailable"
PARTIAL = "partial"
STALE = "stale"

# Repository-relative web base for "open source" links. Azure DevOps is the
# authoritative remote; links are informational and open the file on the host.
AZURE_REPO_WEB = (
    "https://dev.azure.com/peerslate19/portfolio-site/_git/portfolio-site"
    "?path=/{path}"
)

_ISO_DATE = re.compile(r"(20\d{2}-\d{2}-\d{2})")
_DECLARED_DATE = re.compile(
    r"(?:Updated|Verified|Last updated|Updated by|as of)\D{0,12}(20\d{2}-\d{2}-\d{2})",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Low-level, dependency-free helpers
# ---------------------------------------------------------------------------

def _read(path):
    """Return file text, or ``None`` if it cannot be read. Never raises."""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            return handle.read()
    except (OSError, ValueError):
        return None


def _rel(path):
    """Repository-relative POSIX path for display and source links."""
    try:
        return os.path.relpath(path, ROOT).replace(os.sep, "/")
    except ValueError:
        return path.replace(os.sep, "/")


def _source_link(rel_path):
    return AZURE_REPO_WEB.format(path=rel_path)


def _mtime_iso(path):
    try:
        return datetime.fromtimestamp(
            os.path.getmtime(path), tz=timezone.utc
        ).strftime("%Y-%m-%d")
    except (OSError, ValueError):
        return None


def _declared_date(text):
    """Best human-declared date from a document's own body, or ``None``.

    Prefers an explicit "Updated/Verified <date>" phrase; falls back to the
    first ISO date near the top of the file. This is more truthful than a file
    mtime, which the Azure build step resets when it repackages the artifact.
    """
    if not text:
        return None
    head = text[:1200]
    match = _DECLARED_DATE.search(head)
    if match:
        return match.group(1)
    match = _ISO_DATE.search(head)
    return match.group(1) if match else None


def _first_heading(text, default=None):
    if not text:
        return default
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("#"):
            return line.lstrip("#").strip()
    return default


def _source(rel_path, updated=None, status=OK):
    """A uniform source-reference record for the UI."""
    return {
        "path": rel_path,
        "link": _source_link(rel_path),
        "updated": updated,
        "status": status,
    }


def _format_snapshot_timestamp(value):
    """Render the snapshot's ISO-8601 UTC timestamp like ``generated_at``
    elsewhere on the page, so every "as of" time reads the same way."""
    if not isinstance(value, str):
        return None
    try:
        parsed = datetime.strptime(value, "%Y-%m-%dT%H:%M:%SZ")
    except ValueError:
        return value
    return parsed.strftime("%Y-%m-%d %H:%M UTC")


def _read_snapshot():
    """Parsed ``control_room_snapshot.json``, or ``None`` if missing/invalid.

    Never raises. Unknown/extra fields are ignored for forward compatibility;
    a missing or non-integer ``schema_version`` is treated as absent rather
    than guessed at.
    """
    text = _read(SNAPSHOT_PATH)
    if text is None:
        return None
    try:
        data = json.loads(text)
    except (ValueError, TypeError):
        return None
    if not isinstance(data, dict) or not isinstance(
        data.get("schema_version"), int
    ):
        return None
    return data


def _local_git_head():
    """The local git HEAD (short + full SHA, subject), or ``None``.

    Used only as the *local development* fallback for ``build_identity`` —
    never presented as a deployed build.
    """
    try:
        head = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=ROOT, capture_output=True, text=True, timeout=5,
        )
        subject = subprocess.run(
            ["git", "log", "-1", "--pretty=format:%s"],
            cwd=ROOT, capture_output=True, text=True, timeout=5,
        )
    except (OSError, subprocess.SubprocessError):
        return None

    if head.returncode != 0 or not head.stdout.strip():
        return None

    full_sha = head.stdout.strip()
    return {
        "commit": full_sha[:7],
        "commit_full": full_sha,
        "subject": subject.stdout.strip() if subject.returncode == 0 else None,
    }


# ---------------------------------------------------------------------------
# Minimal YAML-subset reader
# ---------------------------------------------------------------------------
# The governance baseline uses a small, stable YAML subset: mappings, nested
# mappings, block lists of scalars, and block lists of mappings. PyYAML is not a
# project dependency and adding one is out of scope, so this pragmatic reader
# covers exactly that subset. It never raises; on any surprise it returns what
# it parsed so far and the caller degrades gracefully.

def _indent_of(line):
    return len(line) - len(line.lstrip(" "))


def _unquote(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        return value[1:-1]
    return value


def _split_key_value(text):
    """Split ``key: value`` on the first colon that separates a key from a
    value (a colon followed by end-of-string or whitespace). Returns
    ``(key, value_or_None)`` or ``None`` when the line is not a mapping entry.
    """
    match = re.match(r"^([^:#]+?):(?:\s+(.*))?$", text)
    if not match:
        return None
    key = match.group(1).strip()
    value = match.group(2)
    return key, (value.strip() if value is not None else None)


def _parse_yaml_block(lines, index, indent):
    """Parse a block at the given indent. Returns ``(value, next_index)``."""
    container = None
    while index < len(lines):
        raw = lines[index]
        current_indent = _indent_of(raw)
        if current_indent < indent:
            break
        stripped = raw.strip()
        if current_indent > indent:
            # Defensive: unexpected deeper line with no opener — skip it.
            index += 1
            continue

        if stripped.startswith("- "):
            if not isinstance(container, list):
                container = []
            item_text = stripped[2:].strip()
            element_indent = indent + 2
            key_value = _split_key_value(item_text)
            if key_value and key_value[1] is not None:
                # "- key: value" begins a mapping element; absorb sibling keys.
                element = {key_value[0]: _unquote(key_value[1])}
                index += 1
                nested, index = _parse_yaml_block(lines, index, element_indent)
                if isinstance(nested, dict):
                    element.update(nested)
                container.append(element)
            elif key_value:
                # "- key:" opens a nested block for this element.
                index += 1
                nested, index = _parse_yaml_block(lines, index, element_indent)
                container.append({key_value[0]: nested})
            else:
                container.append(_unquote(item_text))
                index += 1
            continue

        key_value = _split_key_value(stripped)
        if key_value is None:
            index += 1
            continue
        key, value = key_value
        if value is not None and value != "":
            if not isinstance(container, dict):
                container = {}
            container[key] = _unquote(value)
            index += 1
        else:
            # "key:" opens a nested block (mapping or list) one level deeper.
            index += 1
            child, index = _parse_yaml_block(lines, index, indent + 2)
            if not isinstance(container, dict):
                container = {}
            container[key] = child
    return (container if container is not None else {}), index


def parse_yaml_subset(text):
    """Parse the governance YAML subset into nested dict/list structures."""
    if not text:
        return {}
    lines = [
        line.rstrip("\n")
        for line in text.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    try:
        value, _ = _parse_yaml_block(lines, 0, 0)
        return value if isinstance(value, dict) else {}
    except Exception:  # pragma: no cover - reader must never break the page
        return {}


# ---------------------------------------------------------------------------
# Providers
# ---------------------------------------------------------------------------

def _baseline():
    """Parsed CURRENT_BASELINE.yaml plus its source record (or unavailable)."""
    path = os.path.join(GOV, "CURRENT_BASELINE.yaml")
    text = _read(path)
    rel = _rel(path)
    if text is None:
        return {}, _source(rel, status=UNAVAILABLE)
    data = parse_yaml_subset(text)
    status = OK if data else PARTIAL
    return data, _source(rel, updated=data.get("updated_at"), status=status)


def _as_list(value):
    if isinstance(value, list):
        return value
    if value in (None, "", {}):
        return []
    return [value]


def _manager_label(manager):
    """Human label for both legacy and portable manager baseline schemas."""
    legacy_tool = manager.get("tool")
    if legacy_tool:
        return legacy_tool

    role = manager.get("role")
    if role == "package_designated_session_manager":
        return "Package-designated session manager"
    if isinstance(role, str) and role.strip():
        return role.replace("_", " ").strip().capitalize()
    return None


def governance_summary():
    """Product authority, manager, theme, and the package roll-up."""
    data, source = _baseline()
    if source["status"] == UNAVAILABLE:
        return {
            "status": UNAVAILABLE,
            "source": source,
            "message": "CURRENT_BASELINE.yaml could not be read.",
        }

    governing = data.get("governing_documents") or {}

    def _doc(name):
        entry = governing.get(name) or {}
        if not isinstance(entry, dict):
            return None
        return {
            "version": entry.get("version"),
            "path": entry.get("path"),
        }

    authority = data.get("authority") or {}
    manager = data.get("manager") or {}
    active = []
    for item in _as_list(data.get("active_packages")):
        if isinstance(item, dict):
            active.append(
                {
                    "id": item.get("id"),
                    "owner": item.get("owner"),
                    "lane": item.get("lane"),
                    "path": item.get("package_path"),
                }
            )

    return {
        "status": OK,
        "source": source,
        "updated_at": data.get("updated_at"),
        "theme": data.get("theme"),
        "manager": {
            "label": _manager_label(manager),
            "tool": manager.get("tool"),
            "role": manager.get("role"),
            "eligible_tools": manager.get("eligible_tools"),
            "delivery_model": manager.get("delivery_model"),
            "responsibilities": manager.get("responsibilities"),
            "current_assignments": manager.get("current_assignments"),
            "decided": manager.get("owner_decision_date"),
        },
        "authority": {
            "remote": authority.get("remote"),
            "host": authority.get("host"),
            "branch": authority.get("branch"),
            "production_url": authority.get("production_url"),
            "application_behavior_commit": authority.get(
                "application_behavior_commit"
            ),
            "application_behavior_pipeline": authority.get(
                "application_behavior_pipeline"
            ),
            "note": authority.get("note"),
        },
        "bible": _doc("bible"),
        "roadmap": _doc("roadmap"),
        "sync_standard": _doc("sync_standard"),
        "completed_packages": _as_list(data.get("completed_packages")),
        "public_safe_slices": _as_list(data.get("public_safe_slices")),
        "holds": _as_list(data.get("holds")),
        "active_packages": active,
        "superseded_documents": _as_list(data.get("superseded_documents")),
        "next_gate": data.get("next_gate"),
    }


def _initiative_title(name, readme):
    """Human title for an initiative: its README's first heading with the
    redundant ``PS-... - `` id prefix removed, or the directory name."""
    title = _first_heading(readme) or name
    return re.sub(r"^" + re.escape(name) + r"\s*[-—:]\s*", "", title)


# README headings that are pure implementation plumbing, not "what is this in
# language I understand" — skipped from the friendly detail view (the full
# README is always one click away via the source link).
_DETAIL_SKIP_HEADINGS = ("writable files", "required reading")
# Headings whose content is the plain-language "what this is" summary.
_DETAIL_SUMMARY_HEADINGS = (
    "outcome", "purpose", "goal", "summary", "objective",
)
_DETAIL_MAX_SECTIONS = 12
_DETAIL_MAX_ITEMS = 40
_DETAIL_MAX_TEXT = 1200


def _clean_inline(text):
    """Reduce a line of Markdown to readable plain text: drop emphasis and code
    markers, turn ``[label](url)`` into ``label``, collapse whitespace. The
    result is rendered as escaped text (never raw HTML)."""
    text = text.replace("**", "").replace("`", "")
    text = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text[:_DETAIL_MAX_TEXT]


def _parse_markdown_blocks(lines):
    """Turn a run of Markdown lines into an ordered list of display blocks:
    ``{"type": "paragraph", "text": ...}`` and
    ``{"type": "list", "ordered": bool, "items": [...]}``. Deliberately small —
    it handles the paragraph/bullet/numbered structure these READMEs use and
    nothing more."""
    blocks = []
    paragraph = []
    items = []
    ordered = None

    def flush_paragraph():
        if paragraph:
            blocks.append(
                {"type": "paragraph", "text": _clean_inline(" ".join(paragraph))}
            )
            paragraph.clear()

    def flush_list():
        nonlocal ordered
        if items:
            blocks.append(
                {
                    "type": "list",
                    "ordered": bool(ordered),
                    "items": [_clean_inline(item) for item in items[:_DETAIL_MAX_ITEMS]],
                }
            )
            items.clear()
        ordered = None

    for raw in lines:
        stripped = raw.strip()
        if not stripped:
            flush_paragraph()
            flush_list()
            continue
        bullet = re.match(r"^[-*]\s+(.*)$", stripped)
        number = re.match(r"^\d+[.)]\s+(.*)$", stripped)
        if bullet:
            flush_paragraph()
            if ordered is True:
                flush_list()
            ordered = False
            items.append(bullet.group(1))
        elif number:
            flush_paragraph()
            if ordered is False:
                flush_list()
            ordered = True
            items.append(number.group(1))
        else:
            flush_list()
            paragraph.append(stripped)

    flush_paragraph()
    flush_list()
    return blocks


def _parse_initiative_detail(text):
    """Structure a README into a plain-language detail view: a headline summary
    (its Outcome/Purpose section) plus the remaining meaningful sections. Pure
    source content — no AI rephrasing, per the dashboard's determinism rule.
    Returns ``None`` when there is no README to read."""
    if not text:
        return None

    intro_lines = []
    sections = []
    current = None
    title_seen = False
    for line in text.splitlines():
        heading = re.match(r"^##\s+(.+)$", line)
        top = re.match(r"^#\s+(.+)$", line)
        if heading:
            if current:
                sections.append(current)
            current = {"heading": _clean_inline(heading.group(1)), "lines": []}
        elif top and not title_seen:
            title_seen = True  # the document title; shown separately
        elif current is not None:
            current["lines"].append(line)
        else:
            intro_lines.append(line)
    if current:
        sections.append(current)

    summary_blocks = None
    kept = []
    for section in sections:
        heading_lower = section["heading"].lower()
        if any(skip in heading_lower for skip in _DETAIL_SKIP_HEADINGS):
            continue
        blocks = _parse_markdown_blocks(section["lines"])
        if not blocks:
            continue
        is_summary = any(
            heading_lower.startswith(key) or key in heading_lower
            for key in _DETAIL_SUMMARY_HEADINGS
        )
        if summary_blocks is None and is_summary:
            summary_blocks = blocks
        else:
            kept.append({"heading": section["heading"], "blocks": blocks})

    if summary_blocks is None:
        intro_blocks = _parse_markdown_blocks(intro_lines)
        if intro_blocks:
            summary_blocks = intro_blocks
        elif kept:
            summary_blocks = kept[0]["blocks"]
            kept = kept[1:]

    return {"summary_blocks": summary_blocks or [], "sections": kept[:_DETAIL_MAX_SECTIONS]}


def initiative_details():
    """Per-initiative plain-language detail keyed by id, for the pop-out view.

    Kept out of ``build_projection`` (and therefore out of ``data.json`` and
    the 90s poll) so the live payload stays lean — this is rendered once into
    the owner page and read there.
    """
    baseline, _ = _baseline()
    active_lookup = {
        item.get("id"): item
        for item in _as_list(baseline.get("active_packages"))
        if isinstance(item, dict)
    }
    details = {}
    if not os.path.isdir(INITIATIVES_DIR):
        return details

    for name in sorted(os.listdir(INITIATIVES_DIR)):
        package_dir = os.path.join(INITIATIVES_DIR, name)
        if not os.path.isdir(package_dir):
            continue
        readme_path = os.path.join(package_dir, "README.md")
        readme = _read(readme_path)
        active = active_lookup.get(name) or {}
        detail = _parse_initiative_detail(readme)
        details[name] = {
            "id": name,
            "title": _initiative_title(name, readme),
            "status": _package_status(name, baseline),
            "owner": active.get("owner"),
            "lane": active.get("lane"),
            "has_readme": readme is not None,
            "has_completion_report": os.path.isfile(
                os.path.join(package_dir, "COMPLETION_REPORT.md")
            ),
            "summary_blocks": detail["summary_blocks"] if detail else [],
            "sections": detail["sections"] if detail else [],
            "source": _source(
                _rel(readme_path),
                status=OK if readme is not None else UNKNOWN,
            ),
        }
    return details


def _package_status(package_id, baseline):
    """Lifecycle state for an initiative id, from authoritative baseline lists."""
    if package_id in set(_as_list(baseline.get("completed_packages"))):
        return "Completed"
    active_ids = {
        item.get("id")
        for item in _as_list(baseline.get("active_packages"))
        if isinstance(item, dict)
    }
    if package_id in active_ids:
        return "Active"
    if package_id in set(_as_list(baseline.get("holds"))):
        return "On hold"
    if package_id in set(_as_list(baseline.get("public_safe_slices"))):
        return "Public-safe slice"
    return "Recorded"


def initiatives():
    """Catalog every ``docs/initiatives/<ID>/`` package with derived state."""
    baseline, _ = _baseline()
    active_lookup = {
        item.get("id"): item
        for item in _as_list(baseline.get("active_packages"))
        if isinstance(item, dict)
    }
    if not os.path.isdir(INITIATIVES_DIR):
        return {"status": UNAVAILABLE, "records": [], "source": _source(
            _rel(INITIATIVES_DIR), status=UNAVAILABLE)}

    records = []
    for name in sorted(os.listdir(INITIATIVES_DIR)):
        package_dir = os.path.join(INITIATIVES_DIR, name)
        if not os.path.isdir(package_dir):
            continue
        readme_path = os.path.join(package_dir, "README.md")
        readme = _read(readme_path)
        completion_path = os.path.join(package_dir, "COMPLETION_REPORT.md")
        has_completion = os.path.isfile(completion_path)
        title = _initiative_title(name, readme)
        status = _package_status(name, baseline)
        active = active_lookup.get(name) or {}
        updated = _declared_date(readme) or _mtime_iso(readme_path)
        records.append(
            {
                "id": name,
                "title": title,
                "status": status,
                "owner": active.get("owner"),
                "lane": active.get("lane"),
                "has_readme": readme is not None,
                "has_completion_report": has_completion,
                "updated": updated,
                "source": _source(
                    _rel(readme_path),
                    updated=updated,
                    status=OK if readme is not None else UNKNOWN,
                ),
            }
        )

    order = {"Active": 0, "On hold": 1, "Public-safe slice": 2,
             "Completed": 3, "Recorded": 4}
    records.sort(key=lambda record: (order.get(record["status"], 9), record["id"]))
    return {"status": OK if records else UNKNOWN, "records": records,
            "source": _source(_rel(INITIATIVES_DIR), status=OK)}


# Documents worth cataloguing beyond the baseline's own governing_documents.
_REGISTER_DOCS = (
    ("docs/governance/CURRENT_STATE.md", "Verified current state", "Canonical"),
    ("docs/governance/ACTIVE_INITIATIVES.md", "Active lanes and assignments",
     "Canonical"),
    ("docs/governance/DOCUMENT_CONTROL.md", "Authority order", "Canonical"),
    ("docs/governance/DECISIONS.md", "Manager decision log", "Canonical"),
    ("docs/governance/OWNER_VISUAL_INTEGRITY_STANDARD.md",
     "Visual integrity standard", "Canonical"),
    ("docs/governance/OWNER_STORY_COMPOSITION_STANDARD.md",
     "Story composition standard", "Canonical"),
    ("docs/governance/MANAGER_SESSION_HANDOFF.md", "Manager handoff", "Supporting"),
    ("docs/AI_WORKFLOW.md", "Shared Git and AI workflow", "Canonical"),
    ("START_HERE.md", "Mandatory startup gate", "Canonical"),
)


def documents_register():
    """Catalog authoritative documents with type, version, and last update."""
    baseline, _ = _baseline()
    governing = baseline.get("governing_documents") or {}
    superseded = set(_as_list(baseline.get("superseded_documents")))
    rows = []

    # 1. The version-bearing governing documents named in the baseline.
    for key, entry in (governing.items() if isinstance(governing, dict) else []):
        if not isinstance(entry, dict) or not entry.get("path"):
            continue
        rel = entry["path"].rstrip("/")
        exists = os.path.exists(os.path.join(ROOT, *rel.split("/")))
        rows.append(
            {
                "title": key.replace("_", " ").title(),
                "type": "Governing document",
                "authority": "Superseded" if rel in superseded else "Canonical",
                "version": entry.get("version"),
                "path": rel,
                "link": _source_link(rel),
                "updated": baseline.get("updated_at"),
                "status": OK if exists else UNAVAILABLE,
            }
        )

    # 2. Named supporting/canonical Markdown records (parse their own date).
    for rel, title, authority in _REGISTER_DOCS:
        abs_path = os.path.join(ROOT, *rel.split("/"))
        text = _read(abs_path)
        rows.append(
            {
                "title": title,
                "type": "Governance record",
                "authority": authority,
                "version": None,
                "path": rel,
                "link": _source_link(rel),
                "updated": _declared_date(text) or _mtime_iso(abs_path),
                "status": OK if text is not None else UNAVAILABLE,
            }
        )

    # 3. Explicitly retired documents, so history is visible, not hidden.
    for rel in sorted(superseded):
        rel = rel.rstrip("/")
        display = rel.split("/")[-1]
        rows.append(
            {
                "title": display,
                "type": "Document",
                "authority": "Superseded",
                "version": None,
                "path": rel if "/" in rel else None,
                "link": _source_link(rel) if "/" in rel else None,
                "updated": None,
                "status": OK,
            }
        )

    return {"status": OK if rows else UNKNOWN, "records": rows,
            "source": _source("docs/governance/CURRENT_BASELINE.yaml", status=OK)}


def decisions():
    """Parse the append-only manager decision log into dated records."""
    path = os.path.join(GOV, "DECISIONS.md")
    text = _read(path)
    rel = _rel(path)
    if text is None:
        return {"status": UNAVAILABLE, "records": [], "source": _source(
            rel, status=UNAVAILABLE)}

    records = []
    current = None
    for line in text.splitlines():
        heading = re.match(r"^##\s+(.*)$", line)
        if heading:
            if current:
                records.append(current)
            title = heading.group(1).strip()
            date_match = _ISO_DATE.search(title)
            current = {
                "date": date_match.group(1) if date_match else None,
                "title": re.sub(r"^20\d{2}-\d{2}-\d{2}\s*[-—:]\s*", "", title),
                "points": [],
            }
        elif current is not None:
            bullet = re.match(r"^[-*]\s+(.*)$", line.strip())
            if bullet:
                current["points"].append(bullet.group(1).strip())
    if current:
        records.append(current)

    # Newest first when dates are present.
    records.sort(key=lambda record: record["date"] or "", reverse=True)
    return {"status": OK if records else UNKNOWN, "records": records,
            "source": _source(rel, updated=_declared_date(text), status=OK)}


def delivery_health():
    """Deployment/pipeline facts the repository records, plus a truthful note
    that no *live* Azure DevOps integration is configured for this dashboard.

    The brief forbids adding broad delivery-platform credentials merely to
    populate the dashboard, and this build handles no tokens. So Delivery Health
    shows what the authoritative baseline records and clearly marks the live
    integration as unavailable rather than manufacturing green status.
    """
    summary = governance_summary()
    if summary["status"] == UNAVAILABLE:
        return {"status": UNAVAILABLE, "source": summary["source"],
                "live_integration": UNAVAILABLE, "records": []}

    authority = summary["authority"]
    records = [
        {
            "label": "Last recorded application-behaviour release",
            "value": authority.get("application_behavior_commit"),
            "detail": (
                "pipeline "
                f"{authority.get('application_behavior_pipeline')}"
                if authority.get("application_behavior_pipeline")
                else None
            ),
            "status": OK if authority.get("application_behavior_commit")
            else UNKNOWN,
        },
        {
            "label": "Production URL",
            "value": authority.get("production_url"),
            "detail": "Recorded in baseline; not probed live by this dashboard.",
            "status": OK if authority.get("production_url") else UNKNOWN,
        },
    ]
    return {
        "status": OK,
        "source": summary["source"],
        # No live Azure DevOps Boards/Pipelines integration is configured; this
        # dashboard reads no delivery credentials.
        "live_integration": UNAVAILABLE,
        "live_integration_note": (
            "Live Azure DevOps Pipelines/Boards integration is not configured. "
            "Figures below are the repository's recorded release facts, not a "
            "live probe."
        ),
        "records": records,
    }


def recent_changes(limit=15):
    """A source-backed change timeline.

    Three tiers, most-current first:
      1. Live local git (development) — always the freshest when present.
      2. The build-time snapshot (production) — captured by the Azure
         pipeline before ``.git`` is stripped from the deployment artifact.
      3. Truthful ``unavailable`` if neither source exists.

    Never invents activity: a tier that cannot be read is skipped, not padded.
    """
    try:
        result = subprocess.run(
            [
                "git",
                "log",
                f"-{int(limit)}",
                "--date=short",
                "--pretty=format:%h\x1f%ad\x1f%an\x1f%s",
            ],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (OSError, subprocess.SubprocessError):
        result = None

    if result and result.returncode == 0 and result.stdout.strip():
        items = []
        for line in result.stdout.splitlines():
            parts = line.split("\x1f")
            if len(parts) != 4:
                continue
            commit, date, author, subject = parts
            items.append(
                {
                    "commit": commit,
                    "date": date,
                    "author": author,
                    "subject": subject,
                }
            )
        return {
            "status": OK if items else UNKNOWN,
            "records": items,
            "tier": "live_git",
            "source": _source(".git", status=OK),
        }

    snapshot = _read_snapshot()
    if snapshot and isinstance(snapshot.get("commits"), list):
        items = [
            {
                "commit": commit.get("commit"),
                "date": commit.get("date"),
                "author": commit.get("author"),
                "subject": commit.get("subject"),
            }
            for commit in snapshot["commits"]
            if isinstance(commit, dict)
        ][:limit]
        return {
            "status": OK if items else UNKNOWN,
            "records": items,
            "tier": "build_snapshot",
            "source": {
                # Never committed (see .gitignore) — no Azure repo link exists
                # for this generated file, so it deliberately carries none.
                "path": "control_room_snapshot.json (generated at build time)",
                "link": None,
                "updated": _format_snapshot_timestamp(
                    snapshot.get("generated_at")
                ),
                "status": OK,
            },
        }

    return {
        "status": UNAVAILABLE,
        "note": (
            "Git history is not available in this environment, and no "
            "build-time snapshot (control_room_snapshot.json) was found. "
            "Production deployment artifacts exclude .git; the Azure "
            "pipeline generates the snapshot before packaging — see "
            "docs/control-room/V2_LIVE_SYNC_SPEC.md."
        ),
        "records": [],
        "tier": None,
        "source": _source(".git", status=UNAVAILABLE),
    }


def build_identity():
    """What commit is actually running right now.

    Production: identifies the deployed artifact's commit and pipeline build
    id from the Tier 0 snapshot. Local development: reports the local git
    HEAD instead, explicitly labelled as local rather than a packaged build —
    the two are never conflated. Feeds the Overview "Production" status card
    and the deployment-drift comparison in ``repository_activity``.
    """
    snapshot = _read_snapshot()
    if snapshot:
        build = snapshot.get("build") or {}
        commits = snapshot.get("commits") or []
        head = commits[0] if commits and isinstance(commits[0], dict) else {}
        full_sha = build.get("source_version")
        return {
            "status": OK,
            "environment": "production_build",
            "commit": (full_sha[:7] if full_sha else head.get("commit")),
            "commit_full": full_sha,
            "subject": head.get("subject"),
            "build_id": build.get("id"),
            "source_branch": build.get("source_branch"),
            "generated_at": _format_snapshot_timestamp(
                snapshot.get("generated_at")
            ),
        }

    local_head = _local_git_head()
    if local_head:
        return {
            "status": OK,
            "environment": "local_development",
            "commit": local_head["commit"],
            "commit_full": local_head["commit_full"],
            "subject": local_head["subject"],
            "build_id": None,
            "source_branch": None,
            "generated_at": None,
        }

    return {
        "status": UNAVAILABLE,
        "environment": "unknown",
        "commit": None,
        "commit_full": None,
        "subject": None,
        "build_id": None,
        "source_branch": None,
        "generated_at": None,
    }


def traceability():
    """Partial-by-design traceability signals derived from available sources.

    We only claim what the files support. Anything the current records cannot
    establish is surfaced as an explicit gap, never silently resolved.
    """
    inits = initiatives()
    gov = governance_summary()
    signals = []

    if gov["status"] == OK:
        active = gov["active_packages"]
        for package in active:
            signals.append(
                {
                    "kind": "Active package traced",
                    "subject": package.get("id"),
                    "detail": (
                        f"Owner {package.get('owner') or 'unknown'} · lane "
                        f"{package.get('lane') or 'unknown'}"
                    ),
                    "status": OK if package.get("path") else PARTIAL,
                }
            )

    if inits["status"] == OK:
        for record in inits["records"]:
            if record["status"] == "Completed" and not record[
                "has_completion_report"
            ]:
                signals.append(
                    {
                        "kind": "Gap: completed without a closeout report",
                        "subject": record["id"],
                        "detail": "Marked complete in baseline; no "
                        "COMPLETION_REPORT.md found.",
                        "status": PARTIAL,
                    }
                )
            if not record["has_readme"]:
                signals.append(
                    {
                        "kind": "Gap: package without a README",
                        "subject": record["id"],
                        "detail": "Initiative directory has no README.md.",
                        "status": PARTIAL,
                    }
                )

    return {
        "status": OK if signals else UNKNOWN,
        "partial": True,
        "note": (
            "Traceability is partial: the current records link initiatives, "
            "owners, and closeout evidence, but do not yet encode a full "
            "requirement → test → deployment chain."
        ),
        "records": signals,
    }


def _current_app_config():
    """The active Flask app's config, or ``{}`` outside a request/app context.

    Imported lazily so this module has no hard Flask dependency and stays
    callable (e.g. from tests or a script) without a running application —
    in that case Tier 1 config reads as empty, which correctly resolves to
    ``not_configured`` rather than raising.
    """
    try:
        from flask import current_app, has_app_context

        if has_app_context():
            return current_app.config
    except RuntimeError:
        pass
    return {}


def _compute_drift(build, activity):
    """Compare the deployed build's commit (Tier 0) against the live `main`
    tip (Tier 1). Never guesses: missing data on either side, or a deployed
    commit that isn't found in the fetched history, is reported ``unknown`` —
    never silently treated as up to date or as a known distance behind.
    """
    deployed_full = (build or {}).get("commit_full")
    main_tip_full = None
    if activity and activity.get("status") in (OK, STALE):
        for branch in activity.get("branches", {}).get("items", []):
            if branch.get("name") == "main":
                main_tip_full = branch.get("commit_full")
                break

    if not deployed_full or not main_tip_full:
        return {"state": "unknown", "detail": None, "pending_commits": []}

    if deployed_full == main_tip_full:
        return {"state": "up_to_date", "detail": None, "pending_commits": []}

    commits = activity.get("commits_main", {}).get("items", [])
    shas = [commit.get("commit_full") for commit in commits]
    if deployed_full not in shas:
        return {"state": "unknown", "detail": None, "pending_commits": []}

    pending = commits[: shas.index(deployed_full)]
    return {
        "state": "behind",
        "detail": f"{len(pending)} commit(s) ahead of the deployed build",
        "pending_commits": pending,
    }


def repository_activity(app_config=None, build=None):
    """Tier 1: live Azure DevOps activity, plus the Tier0×Tier1 drift check.

    ``app_config`` lets callers inject the Flask config explicitly (as
    ``control_room_routes`` does); it defaults to the active app's config
    when available and to ``{}`` otherwise, which correctly reads as
    "not configured" rather than raising outside a request context.
    """
    from services.azure_devops_read import fetch_repository_activity

    if app_config is None:
        app_config = _current_app_config()
    if build is None:
        build = build_identity()

    activity = fetch_repository_activity(app_config)
    return {**activity, "drift": _compute_drift(build, activity)}


def overview(sections):
    """A calm roll-up computed from the already-built sections."""
    gov = sections["governance"]
    inits = sections["initiatives"]
    active_count = len(gov.get("active_packages", [])) if gov[
        "status"] == OK else None
    completed_count = len(gov.get("completed_packages", [])) if gov[
        "status"] == OK else None
    holds = gov.get("holds", []) if gov["status"] == OK else []

    warnings = []
    trace = sections["traceability"]
    if trace["status"] == OK:
        warnings.extend(
            item for item in trace["records"] if item["status"] != OK
        )
    if sections["recent_changes"]["status"] == UNAVAILABLE:
        warnings.append(
            {
                "kind": "Source unavailable",
                "subject": "Recent changes",
                "detail": sections["recent_changes"].get("note"),
                "status": UNAVAILABLE,
            }
        )
    if sections["delivery"].get("live_integration") == UNAVAILABLE:
        warnings.append(
            {
                "kind": "Integration not configured",
                "subject": "Delivery health",
                "detail": sections["delivery"].get("live_integration_note"),
                "status": UNAVAILABLE,
            }
        )
    repo_activity = sections.get("repository_activity") or {}
    if repo_activity.get("status") == "not_configured":
        warnings.append(
            {
                "kind": "Live sync not configured",
                "subject": "Repository activity",
                "detail": repo_activity.get("note"),
                "status": UNAVAILABLE,
            }
        )
    elif repo_activity.get("status") in (UNAVAILABLE, STALE):
        warnings.append(
            {
                "kind": "Live sync "
                + ("unavailable" if repo_activity["status"] == UNAVAILABLE
                   else "stale"),
                "subject": "Repository activity",
                "detail": repo_activity.get("note"),
                "status": repo_activity["status"],
            }
        )
    drift = repo_activity.get("drift") or {}
    if drift.get("state") == "behind":
        warnings.append(
            {
                "kind": "Deployment drift",
                "subject": "Production",
                "detail": drift.get("detail"),
                "status": PARTIAL,
            }
        )

    return {
        "active_count": active_count,
        "completed_count": completed_count,
        "initiative_count": len(inits.get("records", [])),
        "holds": holds,
        "manager": gov.get("manager", {}).get("label") if gov[
            "status"] == OK else None,
        "production_url": gov.get("authority", {}).get("production_url") if gov[
            "status"] == OK else None,
        "bible": gov.get("bible") if gov["status"] == OK else None,
        "roadmap": gov.get("roadmap") if gov["status"] == OK else None,
        "warnings": warnings,
        "next_gate": gov.get("next_gate") if gov["status"] == OK else None,
    }


def build_projection(app_config=None):
    """Assemble the full, JSON-serialisable read-only projection.

    ``app_config`` is the Flask app's config mapping (for Tier 1's Azure
    DevOps settings); callers inside a request may omit it and it is read
    from the active app automatically. Omitting it outside any app context
    (e.g. a script or a test) correctly yields Tier 1 = "not configured"
    rather than raising.
    """
    generated_at = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    build = build_identity()
    sections = {
        "governance": governance_summary(),
        "initiatives": initiatives(),
        "documents": documents_register(),
        "decisions": decisions(),
        "delivery": delivery_health(),
        "recent_changes": recent_changes(),
        "traceability": traceability(),
        "build_identity": build,
        "repository_activity": repository_activity(app_config, build=build),
    }
    sections["overview"] = overview(sections)
    sections["generated_at"] = generated_at
    sections["read_only"] = True
    return sections
