-- PeerSlate Break Feed: 200 Daily Quote Seed Items
-- How to use:
-- 1. Open Azure SQL Database > Query editor.
-- 2. Paste this full file into a new query.
-- 3. Click Run.
-- 4. Then run: SELECT COUNT(*) FROM content_items WHERE content_type = 'quote' AND mood = 'Break';

INSERT INTO content_items
    (content_type, title, body, author, mood, category, tags)
VALUES
('quote', 'Daily Break Quote 001', 'Rest is not a reward. It is part of the process.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 002', 'Small steps still move you forward.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 003', 'Peace grows where hurry loosens its grip.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 004', 'A clear mind often begins with a quiet moment.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 005', 'Step away so you can return with strength.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 006', 'One calm breath can interrupt a heavy day.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 007', 'Progress does not always look loud.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 008', 'Your next best step can be small.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 009', 'Slow is still a direction.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 010', 'Make room for the person you are becoming.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 011', 'Do less with more presence.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 012', 'The pause is where perspective returns.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 013', 'You can reset without starting over.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 014', 'A tired mind needs kindness before strategy.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 015', 'Balance is built one choice at a time.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 016', 'Stillness is not wasted time.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 017', 'Let the day breathe before you judge it.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 018', 'Your pace is allowed to change.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 019', 'Quiet effort often changes the most.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 020', 'A better tomorrow starts with one honest moment today.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 021', 'Step outside; the world is bigger than the problem.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 022', 'Rest sharpens what effort has dulled.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 023', 'The strongest roots grow in patient soil.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 024', 'You do not need to carry everything at once.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 025', 'Clarity often arrives after space.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 026', 'Choose the next right thing, not the whole staircase.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 027', 'Your energy is worth protecting.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 028', 'Begin again, but gentler this time.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 029', 'Growth can be quiet and still be real.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 030', 'A peaceful mind makes better decisions.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 031', 'The best reset is sometimes a single deep breath.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 032', 'Little rituals can rescue long days.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 033', 'Give yourself permission to pause.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 034', 'You are not behind; you are becoming.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 035', 'Every day does not need to be conquered.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 036', 'Leave space for joy to find you.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 037', 'Recovery is part of strength.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 038', 'Light returns slowly, then all at once.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 039', 'The work will wait; your well-being should not.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 040', 'Calm is a skill, not an accident.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 041', 'Take the break before the break takes you.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 042', 'Even a small act of care counts.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 043', 'Your future self is built in quiet minutes.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 044', 'Focus returns when pressure softens.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 045', 'Some days ask for courage; some ask for rest.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 046', 'Let enough be enough for today.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 047', 'Reset the room, reset the mind.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 048', 'One walk can change the shape of a day.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 049', 'Rested people build better things.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 050', 'You can honor ambition without ignoring exhaustion.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 051', 'Make peace with the pace of real change.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 052', 'A steady heart can carry a hard season.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 053', 'The mountain is climbed by ordinary steps.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 054', 'Your worth is not measured by your output.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 055', 'The present moment is a doorway back to yourself.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 056', 'Take care of the body that carries your dreams.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 057', 'Nothing blooms without seasons of quiet.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 058', 'Let today be simple where it can be.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 059', 'A calm beginning can change the whole day.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 060', 'Your mind deserves a softer place to land.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 061', 'Do not confuse stillness with failure.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 062', 'Small comforts are not small when the day is heavy.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 063', 'Protect the habits that protect you.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 064', 'The next breath is a new beginning.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 065', 'Peace is often made, not found.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 066', 'Move your body; free your thoughts.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 067', 'Every reset is a form of progress.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 068', 'The quiet path still leads forward.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 069', 'You can be disciplined and gentle.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 070', 'Rest is fuel for meaningful effort.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 071', 'Make one corner of your day peaceful.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 072', 'Unclench the day from your shoulders.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 073', 'Strength includes knowing when to stop.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 074', 'A good life is built in repeatable moments.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 075', 'Patience is progress without panic.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 076', 'Let your breath be the beginning.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 077', 'Today does not need to contain everything.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 078', 'Calm choices compound over time.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 079', 'Your attention is one of your greatest resources.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 080', 'Give your mind a clean page.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 081', 'Hope can begin as a very small habit.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 082', 'Before you push harder, try breathing deeper.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 083', 'The pause protects the purpose.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 084', 'Small order outside can create calm inside.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 085', 'Take the scenic route through your own thoughts.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 086', 'Renewal starts when you stop rushing past yourself.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 087', 'Even ten quiet minutes can change the story.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 088', 'Make space for your nervous system to exhale.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 089', 'You can return stronger after stepping away.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 090', 'Ease is not laziness; it is wisdom with boundaries.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 091', 'The day is not lost because it was hard.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 092', 'Good rhythms make hard things lighter.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 093', 'Let the simple thing be enough.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 094', 'Some progress is invisible until it is undeniable.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 095', 'Your calm is worth scheduling.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 096', 'Kindness to yourself is practical, not soft.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 097', 'A reset is a decision to continue wisely.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 098', 'Breathe first, solve second.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 099', 'Peace begins where comparison ends.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 100', 'You can be proud of surviving a difficult day.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 101', 'Let your mind come home.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 102', 'A rested soul notices more beauty.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 103', 'The smallest promise kept can rebuild trust with yourself.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 104', 'Do not sprint through a life that needs tending.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 105', 'Your body keeps the score; give it care.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 106', 'One ordinary moment can become a turning point.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 107', 'Soft days can still be strong days.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 108', 'Make room for recovery before resentment arrives.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 109', 'The calm you create today becomes strength tomorrow.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 110', 'Step back far enough to see the whole picture.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 111', 'Even the strongest bow must unbend.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 112', 'Let rest be part of your routine, not your rescue plan.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 113', 'What you repeat becomes your atmosphere.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 114', 'Your peace deserves a place on the calendar.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 115', 'Start with water, breath, and one clear thought.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 116', 'A lighter mind can carry better ideas.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 117', 'Small acts of care are bricks in a better life.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 118', 'Nothing meaningful grows well under constant pressure.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 119', 'Return to what is simple and true.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 120', 'Your day can change with one intentional pause.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 121', 'Let silence do some of the healing.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 122', 'Consistency is easier when the pace is humane.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 123', 'Rest is a strategy for staying in the game.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 124', 'The best version of you also needs sleep.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 125', 'One quiet hour can repair a noisy week.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 126', 'Do not make a permanent story out of a temporary mood.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 127', 'Beauty is easier to notice when you slow down.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 128', 'The wise path leaves room to breathe.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 129', 'Your limits are information, not weakness.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 130', 'Choose restoration before exhaustion becomes the plan.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 131', 'Let today be a practice, not a performance.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 132', 'Every deep breath is a vote for steadiness.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 133', 'You are allowed to need less noise.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 134', 'Progress feels better when peace comes with it.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 135', 'Clear the table; clear a thought.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 136', 'The journey is easier when you stop fighting the pace.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 137', 'A small reset can prevent a larger collapse.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 138', 'Protect your morning if you want to protect your mind.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 139', 'Quiet courage is still courage.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 140', 'Some doors open after you stop forcing them.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 141', 'Your attention grows where you place it.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 142', 'Let your next choice be nourishing.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 143', 'Peace is built in boundaries.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 144', 'Do not overlook the medicine of ordinary things.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 145', 'A steady routine can hold you through uncertain days.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 146', 'Give yourself the grace you would give a friend.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 147', 'Your mind is not a machine; let it rest.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 148', 'Simple habits are often the most powerful.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 149', 'Leave some space between feeling and reacting.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 150', 'Calm is contagious; begin with yourself.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 151', 'Do one thing slowly on purpose.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 152', 'The best break brings you back to yourself.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 153', 'Your future needs your patience today.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 154', 'Every season teaches a different kind of strength.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 155', 'You can be grateful and still need rest.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 156', 'Let the day end without carrying it into tomorrow.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 157', 'A peaceful corner can change the whole room.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 158', 'The first step to clarity is often subtraction.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 159', 'Do not let urgency steal your wisdom.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 160', 'Rest makes room for better effort.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 161', 'Your rhythm does not need to match the crowd.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 162', 'Build a life you do not need to escape from.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 163', 'A gentle reset is still a reset.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 164', 'Some answers arrive after the walk.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 165', 'Your peace is a form of preparation.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 166', 'Give your thoughts somewhere quiet to settle.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 167', 'Start again with less pressure and more presence.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 168', 'Your best work needs your whole self.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 169', 'Let today be enough to begin with.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 170', 'Take the break that keeps the dream alive.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 171', 'Your breath is always a place to return.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 172', 'Small joys are anchors.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 173', 'Do not rush the roots.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 174', 'Let the next hour be lighter than the last.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 175', 'Make space for what restores you.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 176', 'Fatigue is a signal, not a flaw.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 177', 'The strongest plans include recovery.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 178', 'Choose calm before control.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 179', 'Sometimes the brave thing is to stop.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 180', 'Peace grows from repeated small choices.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 181', 'Your life deserves maintenance, not just momentum.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 182', 'Begin where your feet are.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 183', 'Let progress include feeling better.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 184', 'Rest is how effort stays sustainable.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 185', 'Even a quiet day can move you forward.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 186', 'Protect the part of you that still hopes.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 187', 'Pause long enough to hear what you need.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 188', 'The day can be meaningful without being full.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 189', 'Your mind opens when the pressure drops.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 190', 'Take care of the vessel, not just the mission.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 191', 'Let one good habit lead the way.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 192', 'Resetting is not quitting; it is choosing wisely.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 193', 'A calm heart can still be ambitious.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 194', 'Your peace is not a distraction from your purpose.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 195', 'Little by little is a powerful pace.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 196', 'Come back to the present; it has been waiting.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 197', 'Give yourself a softer landing today.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 198', 'The next small action matters.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 199', 'Rest is a bridge, not a detour.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration'),
('quote', 'Daily Break Quote 200', 'Let enough sleep be part of the plan.', 'PeerSlate', 'Break', 'Reset', 'break, daily quote, reset, wellness, inspiration');

SELECT COUNT(*) AS break_quote_count FROM content_items WHERE content_type = 'quote' AND mood = 'Break';
